blank_issues_enabled: true
contact_links:
  - name: ❓ Questions and 💬 Chat
    url: https://discord.gg/55sHTQFxfz
    about: Join us on The @ Platform Discord
  - name: 🗂 Documentation
    url: https://atsign.dev/docs/
    about: Go straight to the documentation