name: at_swarm_load

on:
  workflow_dispatch:
  push:
    branches:
      - "trunk"


jobs:
  build_multi_arch_images:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.7.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.14.1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push at_swarm_load
        id: docker_build
        uses: docker/build-push-action@v2.10.0
        with:
          push: true
          tags: |
            atsigncompany/at_swarm_load:latest
            atsigncompany/at_swarm_load:GHA_${{ github.run_number }}
          platforms: |
            linux/amd64